sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
addons:
  code_climate:
    repo_token: d81350f440f981f869cc37fff76ba610a27e6b2bd442999057e9ad18100216dc
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
